### ISSUE TITLE
Error: record_invalid Invalid parameters {'max_active_deals'

### ISSUE THREAD

**Issue by celshof** [cyberjunky/3commas-cyber-bots#10] opened 2021-11-15 21:34 UTC
My bot had already some activity on it. Max active deals present (20). Started the Galaxyrank bot and  changed to 25 in 3Commas. 15 pair max in galaxyrank.ini Start and update were fine. After first hour the update of pairs is fine, but at the end an error is thrown (BOTID replaced with xxx):
```
2021-11-15 22:18:31 - galaxyscore.py - DEBUG - These pairs are invalid on the 'Binance' market according to 3Commas and were skipped: ['BUSD_BLOK2', 'BUSD_KCS', 'BUSD_RNDR', 'BUSD_POWR', 'BUSD_CSPR', 'BUSD_VRA', 'BUSD_PIT', 'BUSD_CRO', 'BUSD_MIX', 'BUSD_BLZ']
2021-11-15 22:18:31 - galaxyscore.py - DEBUG - Current pairs: ['BUSD_BAT', 'BUSD_FLOW', 'BUSD_INJ', 'BUSD_MATIC', 'BUSD_NANO', 'BUSD_ONE', 'BUSD_QNT', 'BUSD_SKL', 'BUSD_STX', 'BUSD_SXP', 'BUSD_SYS', 'BUSD_TRX', 'BUSD_UTK', 'BUSD_XRP', 'BUSD_XTZ']
New pairs: ['BUSD_NANO', 'BUSD_SYS', 'BUSD_POLY', 'BUSD_QNT', 'BUSD_XLM', 'BUSD_FLOW', 'BUSD_UTK', 'BUSD_SXP', 'BUSD_ANT', 'BUSD_SOL', 'BUSD_STX', 'BUSD_AVAX']
2021-11-15 22:18:31 - connectionpool.py - DEBUG - https://api.3commas.io:443 "PATCH /public/api/ver1/bots/xxx/update HTTP/1.1" 400 144
2021-11-15 22:18:31 - galaxyscore.py - ERROR - Error occurred while updating bot 'BUSD Multi Long Bot' error: Other error occurred: record_invalid Invalid parameters {'max_active_deals': ['must be less than or equal to 24']}.
2021-11-15 22:18:31 - galaxyscore.py - INFO - Next update in 3450 Seconds at 23:16:01

```
My galaxyrank.ini:
```
[settings]
timeinterval = 3450
debug = True
logrotate = 7
botids = [xxx]
numberofpairs = 15
accountmode = real

```

I'm running the latest main version of software (did a GIT PULL just before startup)

**Comment by cyberjunky** [comment] 2021-11-16 09:34
Thanks for reporting, do you have set 'Simultaneous deals per same pair' >1 set then?
Otherwise you need to supply at least 25 pairs to have enough of them for 25 deals.

Galaxyscore was able to find 12 pairs only as new pairs, so I guess you have it set to 2?
Only then the error about 24 makes sense.

You didn't specify a minaltrankscore setting so it seems, a very low value if that one could cause this.
I need more debug information to be able to see what is the cause.

**Comment by celshof** [comment] 2021-11-16 10:21
Correct, I have Simultaneous deals at 2.
I didn't set _minaltrankscore_, but I'm using the galaxyscore bot, so I shouldn't then, right? I didn't set _maxaltrankscore_, that is correct.

Are you looking at something specific with regard to logging or bot-info?

**Comment by cyberjunky** [comment] 2021-11-16 12:15
Above that error in the logfile the bot settings reported and the lunarcrushdata fetched and possibly reported blacklisted/ volume filtering information, but you need to have debug=True set I think.
Are you sure the right bot id was configured, do you have more than one bot managed by galaxyscore?

**Comment by celshof** [comment] 2021-11-17 10:42
I only have one bot and I copy-pasted the ID. Also, first time it did load successfully, so I'm sure that that connection is in order.

This is what happened during the last run today. My blacklist consists mostly of BUSD with things like EUR, Dollar, etc. 

```
2021-11-17 10:45:04 - galaxyscore.py - INFO - Reloaded configuration from '/home/celshof/3commas-cyber-bots/galaxyscore.ini'
2021-11-17 10:45:04 - connectionpool.py - DEBUG - Resetting dropped connection: api.3commas.io
2021-11-17 10:45:04 - connectionpool.py - DEBUG - https://api.3commas.io:443 "GET /public/api/ver1/bots/pairs_black_list HTTP/1.1" 200 None
2021-11-17 10:45:04 - galaxyscore.py - INFO - Fetched 3Commas pairs blacklist OK (11 pairs)
2021-11-17 10:45:04 - connectionpool.py - DEBUG - https://api.3commas.io:443 "GET /public/api/ver1/accounts/currency_rates?market_code=binance&pair=USDT_BTC HTTP/1.1" 200 None
2021-11-17 10:45:04 - galaxyscore.py - INFO - Fetched 3Commas BTC price in USDT 59257.96 OK
2021-11-17 10:45:04 - galaxyscore.py - DEBUG - Current price of BTC is 59257.96 USDT
2021-11-17 10:45:04 - connectionpool.py - DEBUG - Starting new HTTPS connection (1): api.lunarcrush.com:443
2021-11-17 10:45:05 - connectionpool.py - DEBUG - https://api.lunarcrush.com:443 "GET /v2?data=market&type=fast&sort=gs&limit=100&key=Your+LunarCrush+API+Key&desc=True HTTP/1.1" 200 39947
2021-11-17 10:45:05 - galaxyscore.py - DEBUG - rank:  1  acr:  34   gs:75.5   s:VLX      'Velas                    '   volume in btc:      113.59   categories:[]
2021-11-17 10:45:05 - galaxyscore.py - DEBUG - rank:  2  acr:  26   gs:75.5   s:TRADE    'Unitrade                 '   volume in btc:       71.32   categories:['defi', 'erc20']
2021-11-17 10:45:05 - galaxyscore.py - DEBUG - rank:  3  acr: 156   gs:74.0   s:XRP      'XRP                      '   volume in btc:    77321.36   categories:[]
2021-11-17 10:45:05 - galaxyscore.py - DEBUG - rank:  4  acr:   7   gs:74.0   s:CRO      'Crypto.com Chain         '   volume in btc:    13707.03   categories:['erc20']
2021-11-17 10:45:05 - galaxyscore.py - DEBUG - rank:  5  acr: 273   gs:73.5   s:BNB      'Binance Coin             '   volume in btc:    64911.33   categories:['erc20', 'bsc']
2021-11-17 10:45:05 - galaxyscore.py - DEBUG - rank:  6  acr:   6   gs:73.0   s:GALA     'Gala Token               '   volume in btc:    19362.95   categories:['defi', 'erc20']
2021-11-17 10:45:05 - galaxyscore.py - DEBUG - rank:  7  acr: 342   gs:73.0   s:VITE     'VITE                     '   volume in btc:      158.61   categories:['erc20']
2021-11-17 10:45:05 - galaxyscore.py - DEBUG - rank:  8  acr:  70   gs:73.0   s:AQUAGOAT 'Aquagoat                 '   volume in btc:        3.74   categories:[]
2021-11-17 10:45:05 - galaxyscore.py - DEBUG - rank:  9  acr: 207   gs:72.5   s:ETC      'Ethereum Classic         '   volume in btc:    18262.47   categories:[]
2021-11-17 10:45:05 - galaxyscore.py - DEBUG - rank: 10  acr: 176   gs:72.5   s:DUCK     'Unit Protocol Duck       '   volume in btc:        4.03   categories:['defi']
2021-11-17 10:45:05 - galaxyscore.py - DEBUG - rank: 11  acr: 197   gs:71.5   s:BSV      'Bitcoin SV               '   volume in btc:     3675.34   categories:[]
2021-11-17 10:45:05 - galaxyscore.py - DEBUG - rank: 12  acr: 713   gs:71.5   s:SMI      'SafeMoon Inu             '   volume in btc:        9.10   categories:['defi', 'erc20']
2021-11-17 10:45:05 - galaxyscore.py - DEBUG - rank: 13  acr: 281   gs:71.5   s:CUMMIES  'CumRocket                '   volume in btc:        7.36   categories:['defi', 'nft', 'bsc', 'meme']
2021-11-17 10:45:05 - galaxyscore.py - DEBUG - rank: 14  acr:  39   gs:71.0   s:HOKK     'Hokkaidu Inu             '   volume in btc:       38.09   categories:['defi', 'erc20', 'meme']
2021-11-17 10:45:05 - galaxyscore.py - DEBUG - rank: 15  acr: 652   gs:71.0   s:SBR      'Saber                    '   volume in btc:       65.38   categories:[]
2021-11-17 10:45:05 - galaxyscore.py - DEBUG - rank: 16  acr: 100   gs:70.5   s:VAI      'Vai                      '   volume in btc:        5.71   categories:['stablecoin', 'defi', 'bsc']
2021-11-17 10:45:05 - galaxyscore.py - DEBUG - rank: 17  acr: 639   gs:70.5   s:ONT      'Ontology                 '   volume in btc:     2619.01   categories:['dot', 'bsc']
2021-11-17 10:45:05 - galaxyscore.py - DEBUG - rank: 18  acr: 126   gs:70.5   s:SWAP     'Trustswap                '   volume in btc:       20.18   categories:['defi', 'avalanch']
2021-11-17 10:45:05 - galaxyscore.py - DEBUG - rank: 19  acr:  57   gs:70.5   s:LTO      'LTO Network              '   volume in btc:     1328.56   categories:['bsc']
2021-11-17 10:45:05 - galaxyscore.py - DEBUG - rank: 20  acr: 349   gs:70.5   s:SPI      'Shopping.io              '   volume in btc:       10.45   categories:['defi', 'erc20']
2021-11-17 10:45:05 - galaxyscore.py - DEBUG - rank: 21  acr: 123   gs:70.5   s:ECO      'Ormeus Ecosystem         '   volume in btc:        2.82   categories:[]
2021-11-17 10:45:05 - galaxyscore.py - DEBUG - rank: 22  acr: 213   gs:70.5   s:UNI      'Uniswap                  '   volume in btc:     8345.19   categories:['defi', 'erc20']
2021-11-17 10:45:05 - galaxyscore.py - DEBUG - rank: 23  acr:1014   gs:70.0   s:AQUA     'Planet Finance           '   volume in btc:        0.69   categories:['defi', 'nft', 'bsc']
2021-11-17 10:45:05 - galaxyscore.py - DEBUG - rank: 24  acr:  11   gs:70.0   s:RNDR     'Render Token             '   volume in btc:     1423.72   categories:['defi', 'erc20']
2021-11-17 10:45:05 - galaxyscore.py - DEBUG - rank: 25  acr:  38   gs:69.5   s:CHSB     'SwissBorg                '   volume in btc:      110.92   categories:['erc20']
2021-11-17 10:45:05 - galaxyscore.py - DEBUG - rank: 26  acr:1255   gs:69.5   s:XDB      'DigitalBits              '   volume in btc:       58.42   categories:[]
2021-11-17 10:45:05 - galaxyscore.py - DEBUG - rank: 27  acr:   9   gs:69.0   s:OPUL     'Opulous                  '   volume in btc:      268.39   categories:['erc20', 'defi', 'nft', 'bsc']
2021-11-17 10:45:05 - galaxyscore.py - DEBUG - rank: 28  acr: 429   gs:69.0   s:NANO     'Nano                     '   volume in btc:     2008.58   categories:[]
2021-11-17 10:45:05 - galaxyscore.py - DEBUG - rank: 29  acr:  31   gs:68.5   s:MIOTA    'IOTA                     '   volume in btc:     9419.31   categories:[]
2021-11-17 10:45:05 - galaxyscore.py - DEBUG - rank: 30  acr: 223   gs:68.5   s:ALGO     'Algorand                 '   volume in btc:    14562.74   categories:[]
2021-11-17 10:45:05 - galaxyscore.py - DEBUG - rank: 31  acr: 322   gs:68.5   s:SYS      'Syscoin                  '   volume in btc:      426.17   categories:[]
2021-11-17 10:45:05 - galaxyscore.py - DEBUG - rank: 32  acr: 499   gs:68.5   s:ZOO2     'ZooCoin                  '   volume in btc:        5.53   categories:['defi', 'erc20']
2021-11-17 10:45:05 - galaxyscore.py - DEBUG - rank: 33  acr: 895   gs:68.5   s:LEOS     'Leonicorn Swap           '   volume in btc:        4.07   categories:['defi', 'nft', 'bsc']
2021-11-17 10:45:05 - galaxyscore.py - DEBUG - rank: 34  acr: 594   gs:68.0   s:WING     'Wing Finance             '   volume in btc:       91.64   categories:['defi']
2021-11-17 10:45:05 - galaxyscore.py - DEBUG - rank: 35  acr: 653   gs:68.0   s:REVO     'Revomon                  '   volume in btc:       22.55   categories:['erc20', 'nft', 'bsc']
2021-11-17 10:45:05 - galaxyscore.py - DEBUG - rank: 36  acr: 813   gs:68.0   s:PREMIA   'Premia                   '   volume in btc:       11.16   categories:['defi']
2021-11-17 10:45:05 - galaxyscore.py - DEBUG - rank: 37  acr: 204   gs:68.0   s:XVG      'Verge                    '   volume in btc:      527.68   categories:[]
2021-11-17 10:45:05 - galaxyscore.py - DEBUG - rank: 38  acr: 401   gs:68.0   s:UMA      'UMA                      '   volume in btc:     2825.54   categories:['defi', 'erc20']
2021-11-17 10:45:05 - galaxyscore.py - DEBUG - rank: 39  acr: 140   gs:68.0   s:BIFI2    'BiFi                     '   volume in btc:        9.91   categories:['defi', 'erc20', 'bsc']
2021-11-17 10:45:05 - galaxyscore.py - DEBUG - rank: 40  acr:  62   gs:68.0   s:OM       'MANTRA DAO               '   volume in btc:      558.09   categories:['defi', 'dot']
2021-11-17 10:45:05 - galaxyscore.py - DEBUG - rank: 41  acr:  37   gs:68.0   s:HTR      'Hathor                   '   volume in btc:      376.00   categories:[]
2021-11-17 10:45:05 - galaxyscore.py - DEBUG - rank: 42  acr: 263   gs:67.5   s:DG       'Decentral Games          '   volume in btc:       57.52   categories:['nft']
2021-11-17 10:45:05 - galaxyscore.py - DEBUG - rank: 43  acr:  22   gs:67.5   s:CATE     'CATECOIN                 '   volume in btc:       21.37   categories:['defi', 'nft', 'bsc', 'meme']
2021-11-17 10:45:05 - galaxyscore.py - DEBUG - rank: 44  acr: 129   gs:67.5   s:SIN      'SINOVATE                 '   volume in btc:        6.35   categories:[]
2021-11-17 10:45:05 - galaxyscore.py - DEBUG - rank: 45  acr:  91   gs:67.5   s:FYD      'FYDcoin                  '   volume in btc:        1.47   categories:[]
2021-11-17 10:45:05 - galaxyscore.py - DEBUG - rank: 46  acr: 106   gs:67.5   s:ZEE      'ZeroSwap                 '   volume in btc:       36.60   categories:['defi', 'bsc']
2021-11-17 10:45:05 - galaxyscore.py - DEBUG - rank: 47  acr:1329   gs:67.5   s:ZOOT     'Zoo Token                '   volume in btc:        0.75   categories:['defi', 'erc20']
2021-11-17 10:45:05 - galaxyscore.py - DEBUG - rank: 48  acr: 681   gs:67.5   s:PORNROCKET 'PornRocket               '   volume in btc:       15.42   categories:['defi', 'bsc']
2021-11-17 10:45:05 - galaxyscore.py - DEBUG - rank: 49  acr:2226   gs:67.5   s:WGMI     'WGMI                     '   volume in btc:       38.81   categories:['erc20', 'defi']
2021-11-17 10:45:05 - galaxyscore.py - DEBUG - rank: 50  acr:  77   gs:67.0   s:STORJ    'Storj                    '   volume in btc:     3370.51   categories:['erc20']
2021-11-17 10:45:05 - galaxyscore.py - DEBUG - rank: 51  acr:  45   gs:67.0   s:SLIM     'Solanium                 '   volume in btc:       57.62   categories:['defi', 'solana']
2021-11-17 10:45:05 - galaxyscore.py - DEBUG - rank: 52  acr: 539   gs:67.0   s:IRIS     'IRIS Network             '   volume in btc:      100.77   categories:[]
2021-11-17 10:45:05 - galaxyscore.py - DEBUG - rank: 53  acr:  73   gs:67.0   s:VGX      'Voyager Token            '   volume in btc:        3.39   categories:['erc20']
2021-11-17 10:45:05 - galaxyscore.py - DEBUG - rank: 54  acr:  15   gs:67.0   s:TIME2    'Wonderland               '   volume in btc:     2318.14   categories:['avalanch']
2021-11-17 10:45:05 - galaxyscore.py - DEBUG - rank: 55  acr:  10   gs:67.0   s:CRV      'Curve DAO Token          '   volume in btc:     8667.17   categories:['defi', 'erc20']
2021-11-17 10:45:05 - galaxyscore.py - DEBUG - rank: 56  acr: 110   gs:67.0   s:MBX      'MobieCoin                '   volume in btc:       19.64   categories:[]
2021-11-17 10:45:05 - galaxyscore.py - DEBUG - rank: 57  acr:  61   gs:67.0   s:BUSD     'Binance USD              '   volume in btc:   114825.26   categories:['stablecoin', 'erc20', 'bsc']
2021-11-17 10:45:05 - galaxyscore.py - DEBUG - rank: 58  acr: 360   gs:67.0   s:VANCAT   'Vancat                   '   volume in btc:        0.21   categories:['nft']
2021-11-17 10:45:05 - galaxyscore.py - DEBUG - rank: 59  acr: 606   gs:67.0   s:MATH     'MATH                     '   volume in btc:       23.12   categories:['defi', 'dot', 'bsc']
2021-11-17 10:45:05 - galaxyscore.py - DEBUG - rank: 60  acr: 812   gs:66.5   s:ZPAY     'ZoidPay                  '   volume in btc:        0.57   categories:['defi']
2021-11-17 10:45:05 - galaxyscore.py - DEBUG - rank: 61  acr:  74   gs:66.5   s:BABYDOGE 'Baby Doge Coin           '   volume in btc:       54.26   categories:['bsc', 'meme']
2021-11-17 10:45:05 - galaxyscore.py - DEBUG - rank: 62  acr:1002   gs:66.5   s:FXF      'Finxflo                  '   volume in btc:        5.67   categories:['defi', 'erc20']
2021-11-17 10:45:05 - galaxyscore.py - DEBUG - rank: 63  acr:  68   gs:66.5   s:CHNG     'Chainge                  '   volume in btc:       60.30   categories:['defi']
2021-11-17 10:45:05 - galaxyscore.py - DEBUG - rank: 64  acr: 906   gs:66.5   s:HUSD     'HUSD                     '   volume in btc:      673.39   categories:['stablecoin', 'erc20']
2021-11-17 10:45:05 - galaxyscore.py - DEBUG - rank: 65  acr: 502   gs:66.5   s:MERI     'Merebel                  '   volume in btc:        0.47   categories:[]
2021-11-17 10:45:05 - galaxyscore.py - DEBUG - rank: 66  acr: 465   gs:66.5   s:ADK      'Aidos Kuneen             '   volume in btc:        2.09   categories:[]
2021-11-17 10:45:05 - galaxyscore.py - DEBUG - rank: 67  acr: 136   gs:66.5   s:ETH      'Ethereum                 '   volume in btc:   646263.02   categories:[]
2021-11-17 10:45:05 - galaxyscore.py - DEBUG - rank: 68  acr: 372   gs:66.5   s:YFI      'yearn.finance            '   volume in btc:     3409.53   categories:['defi', 'erc20']
2021-11-17 10:45:05 - galaxyscore.py - DEBUG - rank: 69  acr:  42   gs:66.5   s:SOLO     'Sologenic                '   volume in btc:       12.71   categories:[]
2021-11-17 10:45:05 - galaxyscore.py - DEBUG - rank: 70  acr: 888   gs:66.0   s:YF-DAI   'YFDAI Finance            '   volume in btc:        4.31   categories:['defi']
2021-11-17 10:45:05 - galaxyscore.py - DEBUG - rank: 71  acr: 851   gs:66.0   s:POSI     'Position Token           '   volume in btc:       57.64   categories:['defi', 'nft', 'bsc']
2021-11-17 10:45:05 - galaxyscore.py - DEBUG - rank: 72  acr: 182   gs:66.0   s:COMBO    'Furucombo                '   volume in btc:        3.22   categories:['defi']
2021-11-17 10:45:05 - galaxyscore.py - DEBUG - rank: 73  acr: 860   gs:66.0   s:HAM      'HAMSTER                  '   volume in btc:        0.64   categories:['bsc']
2021-11-17 10:45:05 - galaxyscore.py - DEBUG - rank: 74  acr:1022   gs:66.0   s:FEVR     'RealFevr                 '   volume in btc:        7.19   categories:['erc20', 'nft', 'bsc']
2021-11-17 10:45:05 - galaxyscore.py - DEBUG - rank: 75  acr: 870   gs:66.0   s:ATRI     'Atari                    '   volume in btc:       12.79   categories:['nft']
2021-11-17 10:45:05 - galaxyscore.py - DEBUG - rank: 76  acr: 470   gs:66.0   s:STRONG   'STRONG                   '   volume in btc:      191.51   categories:['defi', 'erc20']
2021-11-17 10:45:05 - galaxyscore.py - DEBUG - rank: 77  acr: 115   gs:66.0   s:MBL      'MovieBloc                '   volume in btc:     1503.64   categories:[]
2021-11-17 10:45:05 - galaxyscore.py - DEBUG - rank: 78  acr: 103   gs:66.0   s:UST      'TerraUSD                 '   volume in btc:     2160.31   categories:['stablecoin', 'terra']
2021-11-17 10:45:05 - galaxyscore.py - DEBUG - rank: 79  acr: 121   gs:66.0   s:ERN      'Ethernity Chain          '   volume in btc:      229.92   categories:['erc20', 'nft']
2021-11-17 10:45:05 - galaxyscore.py - DEBUG - rank: 80  acr: 784   gs:65.5   s:DCN      'Dentacoin                '   volume in btc:        4.91   categories:[]
2021-11-17 10:45:05 - galaxyscore.py - DEBUG - rank: 81  acr: 431   gs:65.5   s:KEEP     'Keep Network             '   volume in btc:     1174.83   categories:['defi', 'erc20']
2021-11-17 10:45:05 - galaxyscore.py - DEBUG - rank: 82  acr:  79   gs:65.5   s:KAWA     'Kawakami Inu V2          '   volume in btc:        7.86   categories:['defi', 'erc20', 'meme']
2021-11-17 10:45:05 - galaxyscore.py - DEBUG - rank: 83  acr:2229   gs:65.5   s:CISLA    'Crypto Island            '   volume in btc:        3.38   categories:['defi', 'nft', 'bsc']
2021-11-17 10:45:05 - galaxyscore.py - DEBUG - rank: 84  acr: 543   gs:65.5   s:SPIRIT   'SpiritSwap               '   volume in btc:       22.46   categories:['defi', 'erc20']
2021-11-17 10:45:05 - galaxyscore.py - DEBUG - rank: 85  acr:  49   gs:65.5   s:META     'Metadium                 '   volume in btc:      640.89   categories:[]
2021-11-17 10:45:05 - galaxyscore.py - DEBUG - rank: 86  acr: 574   gs:65.0   s:ASS      'Australian Safe Shepherd '   volume in btc:       17.38   categories:['bsc', 'meme']
2021-11-17 10:45:05 - galaxyscore.py - DEBUG - rank: 87  acr: 169   gs:65.0   s:BTR      'Bitrue Coin              '   volume in btc:      185.38   categories:['erc20']
2021-11-17 10:45:05 - galaxyscore.py - DEBUG - rank: 88  acr: 338   gs:65.0   s:NEAR     'Near Protocol            '   volume in btc:     9033.77   categories:[]
2021-11-17 10:45:05 - galaxyscore.py - DEBUG - rank: 89  acr: 116   gs:65.0   s:SUSHI    'Sushi Swap               '   volume in btc:     6478.94   categories:['defi', 'erc20']
2021-11-17 10:45:05 - galaxyscore.py - DEBUG - rank: 90  acr: 802   gs:65.0   s:ATM      'Atletico Madrid Fan Token'   volume in btc:      111.98   categories:['chiliz']
2021-11-17 10:45:05 - galaxyscore.py - DEBUG - rank: 91  acr: 998   gs:65.0   s:GFI      'Gravity Finance          '   volume in btc:        1.10   categories:[]
2021-11-17 10:45:05 - galaxyscore.py - DEBUG - rank: 92  acr: 205   gs:65.0   s:UNO      'Uno Re                   '   volume in btc:       39.58   categories:['defi', 'erc20', 'dot', 'bsc']
2021-11-17 10:45:05 - galaxyscore.py - DEBUG - rank: 93  acr: 546   gs:64.5   s:ADD      'Add.xyz                  '   volume in btc:        0.20   categories:['defi']
2021-11-17 10:45:05 - galaxyscore.py - DEBUG - rank: 94  acr: 751   gs:64.5   s:EMAX     'EthereumMax              '   volume in btc:        2.25   categories:['erc20']
2021-11-17 10:45:05 - galaxyscore.py - DEBUG - rank: 95  acr:   4   gs:64.5   s:AVAX     'Avalanche                '   volume in btc:    56165.99   categories:['defi', 'avalanch']
2021-11-17 10:45:05 - galaxyscore.py - DEBUG - rank: 96  acr:1670   gs:64.5   s:DRM      'Dreamcoin                '   volume in btc:        3.83   categories:[]
2021-11-17 10:45:05 - galaxyscore.py - DEBUG - rank: 97  acr: 192   gs:64.5   s:SFUND    'Seedify.fund             '   volume in btc:       57.81   categories:['defi', 'bsc']
2021-11-17 10:45:05 - galaxyscore.py - DEBUG - rank: 98  acr:  81   gs:64.5   s:TIME     'Chrono.tech              '   volume in btc:        1.33   categories:['erc20']
2021-11-17 10:45:05 - galaxyscore.py - DEBUG - rank: 99  acr: 175   gs:64.5   s:YLDX     'Yield App                '   volume in btc:       13.92   categories:['defi', 'erc20']
2021-11-17 10:45:05 - galaxyscore.py - DEBUG - rank:100  acr:1042   gs:64.5   s:CFX      'Conflux Network          '   volume in btc:      222.42   categories:[]
2021-11-17 10:45:05 - galaxyscore.py - INFO - Fetched LunarCrush ranking OK (100 coins)
2021-11-17 10:45:06 - connectionpool.py - DEBUG - https://api.3commas.io:443 "GET /public/api/ver1/bots/6901672/show HTTP/1.1" 200 None
2021-11-17 10:45:06 - galaxyscore.py - DEBUG - Bot base currency: BUSD
2021-11-17 10:45:06 - galaxyscore.py - DEBUG - Bot exchange: Binance
2021-11-17 10:45:06 - galaxyscore.py - DEBUG - Bot minimal 24h BTC volume: 500.0
2021-11-17 10:45:06 - connectionpool.py - DEBUG - https://api.3commas.io:443 "GET /public/api/ver1/accounts/market_pairs?market_code=binance HTTP/1.1" 200 None
2021-11-17 10:45:06 - galaxyscore.py - INFO - Fetched 3Commas market data for binance OK (1327 pairs)
2021-11-17 10:45:06 - galaxyscore.py - DEBUG - Quote currency 'VLX' does not have enough 24h BTC volume (113.58957783899412), skipping
2021-11-17 10:45:06 - galaxyscore.py - DEBUG - Quote currency 'TRADE' does not have enough 24h BTC volume (71.31736563324151), skipping
2021-11-17 10:45:06 - galaxyscore.py - DEBUG - Quote currency 'VITE' does not have enough 24h BTC volume (158.6074424431756), skipping
2021-11-17 10:45:06 - galaxyscore.py - DEBUG - Quote currency 'AQUAGOAT' does not have enough 24h BTC volume (3.739822970618631), skipping
2021-11-17 10:45:06 - galaxyscore.py - DEBUG - Quote currency 'DUCK' does not have enough 24h BTC volume (4.0264536612465225), skipping
2021-11-17 10:45:06 - galaxyscore.py - DEBUG - Quote currency 'SMI' does not have enough 24h BTC volume (9.101957272913209), skipping
2021-11-17 10:45:06 - galaxyscore.py - DEBUG - Quote currency 'CUMMIES' does not have enough 24h BTC volume (7.3602884743248), skipping
2021-11-17 10:45:06 - galaxyscore.py - DEBUG - Quote currency 'HOKK' does not have enough 24h BTC volume (38.08926328209746), skipping
2021-11-17 10:45:06 - galaxyscore.py - DEBUG - Quote currency 'SBR' does not have enough 24h BTC volume (65.3820598954132), skipping
2021-11-17 10:45:06 - galaxyscore.py - DEBUG - Quote currency 'VAI' does not have enough 24h BTC volume (5.713470392838363), skipping
2021-11-17 10:45:06 - galaxyscore.py - DEBUG - Quote currency 'SWAP' does not have enough 24h BTC volume (20.179316669017968), skipping
2021-11-17 10:45:06 - galaxyscore.py - DEBUG - Quote currency 'SPI' does not have enough 24h BTC volume (10.449872894713216), skipping
2021-11-17 10:45:06 - galaxyscore.py - DEBUG - Quote currency 'ECO' does not have enough 24h BTC volume (2.815424628184973), skipping
2021-11-17 10:45:06 - galaxyscore.py - DEBUG - Quote currency 'AQUA' does not have enough 24h BTC volume (0.6904939015787922), skipping
2021-11-17 10:45:06 - galaxyscore.py - DEBUG - Quote currency 'CHSB' does not have enough 24h BTC volume (110.91583021082738), skipping
2021-11-17 10:45:06 - galaxyscore.py - DEBUG - Quote currency 'XDB' does not have enough 24h BTC volume (58.42498644907789), skipping
2021-11-17 10:45:06 - galaxyscore.py - DEBUG - Quote currency 'OPUL' does not have enough 24h BTC volume (268.3901934862422), skipping
2021-11-17 10:45:06 - galaxyscore.py - DEBUG - Quote currency 'SYS' does not have enough 24h BTC volume (426.1684470744521), skipping
2021-11-17 10:45:06 - galaxyscore.py - DEBUG - Quote currency 'ZOO2' does not have enough 24h BTC volume (5.530723467362022), skipping
2021-11-17 10:45:06 - galaxyscore.py - DEBUG - Quote currency 'LEOS' does not have enough 24h BTC volume (4.074582553972496), skipping
2021-11-17 10:45:06 - galaxyscore.py - DEBUG - Quote currency 'WING' does not have enough 24h BTC volume (91.64326530984192), skipping
2021-11-17 10:45:06 - galaxyscore.py - DEBUG - Quote currency 'REVO' does not have enough 24h BTC volume (22.545447902695265), skipping
2021-11-17 10:45:06 - galaxyscore.py - DEBUG - Quote currency 'PREMIA' does not have enough 24h BTC volume (11.162954141519553), skipping
2021-11-17 10:45:06 - galaxyscore.py - DEBUG - Quote currency 'BIFI2' does not have enough 24h BTC volume (9.905895849266496), skipping
2021-11-17 10:45:06 - galaxyscore.py - DEBUG - Quote currency 'HTR' does not have enough 24h BTC volume (376.00255307472617), skipping
2021-11-17 10:45:06 - galaxyscore.py - DEBUG - Quote currency 'DG' does not have enough 24h BTC volume (57.51786257913705), skipping
2021-11-17 10:45:06 - galaxyscore.py - DEBUG - Quote currency 'CATE' does not have enough 24h BTC volume (21.37388057233155), skipping
2021-11-17 10:45:06 - galaxyscore.py - DEBUG - Quote currency 'SIN' does not have enough 24h BTC volume (6.353057378283019), skipping
2021-11-17 10:45:06 - galaxyscore.py - DEBUG - Quote currency 'FYD' does not have enough 24h BTC volume (1.4696997669173897), skipping
2021-11-17 10:45:06 - galaxyscore.py - DEBUG - Quote currency 'ZEE' does not have enough 24h BTC volume (36.604840598630126), skipping
2021-11-17 10:45:06 - galaxyscore.py - DEBUG - Quote currency 'ZOOT' does not have enough 24h BTC volume (0.7451748254580481), skipping
2021-11-17 10:45:06 - galaxyscore.py - DEBUG - Quote currency 'PORNROCKET' does not have enough 24h BTC volume (15.418818163838242), skipping
2021-11-17 10:45:06 - galaxyscore.py - DEBUG - Quote currency 'WGMI' does not have enough 24h BTC volume (38.81323876150985), skipping
2021-11-17 10:45:06 - galaxyscore.py - DEBUG - These pairs are on your blacklist and were skipped: []
2021-11-17 10:45:06 - galaxyscore.py - DEBUG - These pairs are invalid on the 'Binance' market according to 3Commas and were skipped: ['BUSD_CRO', 'BUSD_BSV', 'BUSD_RNDR', 'BUSD_MIOTA', 'BUSD_UMA']
2021-11-17 10:45:06 - galaxyscore.py - DEBUG - Current pairs: ['BUSD_BAT', 'BUSD_FLOW', 'BUSD_INJ', 'BUSD_MATIC', 'BUSD_NANO', 'BUSD_ONE', 'BUSD_QNT', 'BUSD_SKL', 'BUSD_STX', 'BUSD_SXP', 'BUSD_SYS', 'BUSD_TRX', 'BUSD_UTK', 'BUSD_XRP', 'BUSD_XTZ']
New pairs: ['BUSD_XRP', 'BUSD_BNB', 'BUSD_GALA', 'BUSD_ETC', 'BUSD_ONT', 'BUSD_LTO', 'BUSD_UNI', 'BUSD_NANO', 'BUSD_ALGO', 'BUSD_XVG', 'BUSD_OM', 'BUSD_STORJ']
2021-11-17 10:45:06 - connectionpool.py - DEBUG - https://api.3commas.io:443 "PATCH /public/api/ver1/bots/6901672/update HTTP/1.1" 400 144
2021-11-17 10:45:06 - galaxyscore.py - ERROR - Error occurred while updating bot 'BUSD Multi Long Bot' error: Other error occurred: record_invalid Invalid parameters {'max_active_deals': ['must be less than or equal to 24']}.
2021-11-17 10:45:06 - galaxyscore.py - INFO - Next update in 3450 Seconds at 11:42:36
celshof@h2797212:~/3commas-cyber-bots/logs$

```

**Comment by cyberjunky** [comment] 2021-11-17 13:06
Hi, strange error which I would like to understand and solve this. Are Dutch and on Discord byany chance, maybe we can connect and you are willing to share the bot (in a PM) so I can copy and test it

**Comment by celshof** [comment] 2021-11-17 15:59
Discord is prima :)

**Comment by cyberjunky** [comment] 2021-11-18 11:18
I cannot seem to reproduce it, even running the same bot as you shared (although I saw it has a different max deals of 30)

**Comment by celshof** [comment] 2021-11-18 13:31
I tried some tweaking to see if the result changed. I'll do a "have you tried turning it off and on again" and see what that does. Shall I do a PULL after I stopped the bot?

**Comment by cyberjunky** [comment] 2021-11-18 13:42
Yeah why not.. Wouldn't hurt, unless I introduce new bugs ;-)

**Comment by cyberjunky** [comment] 2021-11-22 20:47
Closing cannot reproduce, maybe has to do with making changes to running bot without stop/start. Can open new issue if needed.

**Closed by cyberjunky** 2021-11-22 20:47 UTC
